# **Numpy Tricks**

In [2]:
import numpy as np

# np.sort
return sorted copy of a array

In [3]:
a=np.random.randint(1,100,15)
print("Random array: ",a)
print("sorting by 0 - nth: ",np.sort(a))
print("reverse sorting: ", np.sort(a)[::-1])

Random array:  [ 5 59 49  8 13  6 40 84 63 49 72 63 21  8 72]
sorting by 0 - nth:  [ 5  6  8  8 13 21 40 49 49 59 63 63 72 72 84]
reverse sorting:  [84 72 72 63 63 59 49 49 40 21 13  8  8  6  5]


In [4]:
# sort by rows 
b=np.random.randint(1,100,24).reshape(6,4)
print(b)
print()
np.sort(b)

[[13 11 81 80]
 [45 10 64 26]
 [65 82 41 78]
 [85 10 87 31]
 [77  2 72 99]
 [22 50 19 78]]



array([[11, 13, 80, 81],
       [10, 26, 45, 64],
       [41, 65, 78, 82],
       [10, 31, 85, 87],
       [ 2, 72, 77, 99],
       [19, 22, 50, 78]])

In [5]:
# sort by columns
print(b)
print()
np.sort(b,axis=0)

[[13 11 81 80]
 [45 10 64 26]
 [65 82 41 78]
 [85 10 87 31]
 [77  2 72 99]
 [22 50 19 78]]



array([[13,  2, 19, 26],
       [22, 10, 41, 31],
       [45, 10, 64, 78],
       [65, 11, 72, 78],
       [77, 50, 81, 80],
       [85, 82, 87, 99]])

In [6]:
#reverse sorting
np.sort(b,axis=0)[::-1]

array([[85, 82, 87, 99],
       [77, 50, 81, 80],
       [65, 11, 72, 78],
       [45, 10, 64, 78],
       [22, 10, 41, 31],
       [13,  2, 19, 26]])

In [7]:
np.sort(b)[::-1]

array([[19, 22, 50, 78],
       [ 2, 72, 77, 99],
       [10, 31, 85, 87],
       [41, 65, 78, 82],
       [10, 26, 45, 64],
       [11, 13, 80, 81]])

# np.append()
the numpy .append() appends values along the mentioned axis at the end of the array

In [8]:
# np.append(name of array, values append into last)
print(a)
print(np.append(a,200)) # append single values
print(np.append(a,[100,20,30,500,78,19])) # append mulitple value at once

[ 5 59 49  8 13  6 40 84 63 49 72 63 21  8 72]
[  5  59  49   8  13   6  40  84  63  49  72  63  21   8  72 200]
[  5  59  49   8  13   6  40  84  63  49  72  63  21   8  72 100  20  30
 500  78  19]


In [9]:
# append in 2D array 
# add 1 new columns in array
print(b)
np.append()

[[13 11 81 80]
 [45 10 64 26]
 [65 82 41 78]
 [85 10 87 31]
 [77  2 72 99]
 [22 50 19 78]]


TypeError: append() missing 2 required positional arguments: 'arr' and 'values'

In [14]:
#np.append(var(array name), np.ones(what you append)(var.shape(shape of item)[0th position to], 1th position),axis=1 )
np.append(b, np.ones((b.shape[0],1)),axis=1)

array([[13., 11., 81., 80.,  1.],
       [45., 10., 64., 26.,  1.],
       [65., 82., 41., 78.,  1.],
       [85., 10., 87., 31.,  1.],
       [77.,  2., 72., 99.,  1.],
       [22., 50., 19., 78.,  1.]])

In [11]:
# add random number
np.append(b, np.random.random((b.shape[0],1)),axis=1)

array([[13.        , 11.        , 81.        , 80.        ,  0.82851685],
       [45.        , 10.        , 64.        , 26.        ,  0.86200006],
       [65.        , 82.        , 41.        , 78.        ,  0.99965292],
       [85.        , 10.        , 87.        , 31.        ,  0.64519747],
       [77.        ,  2.        , 72.        , 99.        ,  0.91939073],
       [22.        , 50.        , 19.        , 78.        ,  0.11081366]])

# np.concatenate
numpy.concatenate() functions concatenate a sequance of arrays along an existing axis. 

In [15]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [16]:
print(np.concatenate((c,d),axis=0)) # axis is not mandatory for row concatenation only required when you do concatenate array by columns by using axis=1
print()
print(np.concatenate((c,d),axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


# np.unique
with the help of np.unique() methods, we can get the unique value from an array given as perameter in np.unique() methods. 

In [ ]:
e=[1,1,2,3,4,4,6,7,8,9,9]
f=[[1,2,3,1],[1,2,3,2]]
print(e)
print(f)

In [134]:
print(np.unique(e))
print(np.unique(f))

[1 2 3 4 6 7 8 9]
[1 2 3]


### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array      
you can convert 1d array into 2d and 3d into 4d.


In [17]:
print(a)
print(np.expand_dims(a,axis=0).shape)
print()
a

[ 5 59 49  8 13  6 40 84 63 49 72 63 21  8 72]
(1, 15)



array([ 5, 59, 49,  8, 13,  6, 40, 84, 63, 49, 72, 63, 21,  8, 72])

In [136]:
print(np.expand_dims(a,axis=1).shape)

(15, 1)


### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.   
will give index position of the numbers according to the condition.

you can also replace the value accoring to the condition or index number

In [137]:
a=np.random.randint(1,100,15)
a

array([44, 91, 67, 45, 30, 13, 28, 63, 84, 91, 27, 54,  7, 22, 37])

In [138]:
np.where(a)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       dtype=int64),)

In [139]:
# will give index number above the value greater than 50.
print(np.where(a>50))

(array([ 1,  2,  7,  8,  9, 11], dtype=int64),)


In [140]:
print("even number index number :",np.where(a%2==0))

even number index number : (array([ 0,  4,  6,  8, 11, 13], dtype=int64),)


># replace all values >50 with 0
np.where(condition, ture, false)


In [141]:
print(np.where(a>50,0,a))

[44  0  0 45 30 13 28  0  0  0 27  0  7 22 37]


In [142]:
print(np.where(a>50,1,a))

[44  1  1 45 30 13 28  1  1  1 27  1  7 22 37]


# np.argmax and np.argmin

The numpy.argmax() function returns indices of the max element of the array in a particular axis.    
 will give index postion of the max/larger number in the array

In [143]:
a

array([44, 91, 67, 45, 30, 13, 28, 63, 84, 91, 27, 54,  7, 22, 37])

In [144]:
np.argmax(a)

1

In [145]:
print(b)
print()
print(np.argmax(b,axis=0))
print()
print(np.argmax(b,axis=1))

[[10 19 78 72]
 [85 40 90 12]
 [43 88 38 69]
 [84 85 88 82]
 [65 57 89 12]
 [99 40 63 17]]

[5 2 1 3]

[2 2 1 2 2 0]


In [146]:
np.argmin(a)

12

In [147]:
np.argmin(b)

0

In [148]:
print(b)
print()
print(np.argmin(b,axis=0))
print()
print(np.argmin(b,axis=1))

[[10 19 78 72]
 [85 40 90 12]
 [43 88 38 69]
 [84 85 88 82]
 [65 57 89 12]
 [99 40 63 17]]

[0 0 2 1]

[0 3 2 3 3 3]


# np.cumsum(cumulative sum)

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.


In [18]:
a=np.random.randint(0,100,20)
a

array([65, 29, 60, 15, 10,  1, 96, 35, 75, 76, 75, 68, 29, 29, 15, 82, 94,
       45,  5, 51])

In [19]:
np.cumsum(a)

array([ 65,  94, 154, 169, 179, 180, 276, 311, 386, 462, 537, 605, 634,
       663, 678, 760, 854, 899, 904, 955])

In [151]:
b

array([[10, 19, 78, 72],
       [85, 40, 90, 12],
       [43, 88, 38, 69],
       [84, 85, 88, 82],
       [65, 57, 89, 12],
       [99, 40, 63, 17]])

In [152]:
np.cumsum(b) # if didn't give axis value it will return 1D array

array([  10,   29,  107,  179,  264,  304,  394,  406,  449,  537,  575,
        644,  728,  813,  901,  983, 1048, 1105, 1194, 1206, 1305, 1345,
       1408, 1425])

In [153]:
np.cumsum(b,axis=0) # row wise cumulative_sum

array([[ 10,  19,  78,  72],
       [ 95,  59, 168,  84],
       [138, 147, 206, 153],
       [222, 232, 294, 235],
       [287, 289, 383, 247],
       [386, 329, 446, 264]])

In [154]:
np.cumsum(b,axis=1) # column wise cumulative_sum

array([[ 10,  29, 107, 179],
       [ 85, 125, 215, 227],
       [ 43, 131, 169, 238],
       [ 84, 169, 257, 339],
       [ 65, 122, 211, 223],
       [ 99, 139, 202, 219]])

# np.cumprod() cumulative product-> multiply

numpy.cumprod() function is used when we want to compute the cumulative multiply of array elements over a given axis.

will multiply the sequance of the array

In [156]:
np.cumprod(a)

array([         22,        1716,      137280,     8785920,   193290240,
         966451200,   966451200,   537288704, -1051181056,   392708096,
       -1521188864,    -2621440,   -39321600,  1070596096,  -138412032,
           8388608,   545259520,  -687865856,  -369098752, -1375731712])

In [157]:
np.cumprod(b)

array([         10,         190,       14820,     1067040,    90698400,
        -667031296,    96725504,  1160706048, -1629247488, -1639858176,
        2109898752,  -445874176,  1201274880,  -970850304,   464519168,
        -564133888,  1986002944,  1533018112, -1000341504,   880803840,
        1300234240,   469762048,  -469762048,   603979776])

In [158]:
np.cumprod(b,axis=0) # multiply row wise

array([[         10,          19,          78,          72],
       [        850,         760,        7020,         864],
       [      36550,       66880,      266760,       59616],
       [    3070200,     5684800,    23474880,     4888512],
       [  199563000,   324033600,  2089264320,    58662144],
       [-1718099480,    76442112, -1520334016,   997256448]])

In [160]:
np.cumprod(b,axis=1) # multiply column wise

array([[      10,      190,    14820,  1067040],
       [      85,     3400,   306000,  3672000],
       [      43,     3784,   143792,  9921648],
       [      84,     7140,   628320, 51522240],
       [      65,     3705,   329745,  3956940],
       [      99,     3960,   249480,  4241160]])

# np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

will return percentile of max number

In [161]:
a

array([22, 78, 80, 64, 22,  5,  1,  5, 54, 65, 18, 48, 15, 82, 44, 62, 65,
       46, 38, 27])

In [164]:
np.percentile(a,100)

82.0

In [167]:
np.percentile(a,50)

45.0

In [166]:
# average of array or 50th percentile 
np.median(a)

45.0

# np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

histogram = will count the numbers under the frequency and give the histogram number for plot, bar, pie chart etc.

syntax:     
np.histogram(array name, bins=[frequency range])


In [173]:
a

array([22, 78, 80, 64, 22,  5,  1,  5, 54, 65, 18, 48, 15, 82, 44, 62, 65,
       46, 38, 27])

In [174]:
np.histogram(a,bins=[10,20,30,40,50,60,70,80,90,100])


(array([2, 3, 1, 3, 1, 4, 1, 2, 0], dtype=int64),
 array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# np.corrcoef

Return Pearson product-moment correlation coefficients.

In [175]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# np.isin

With the help of numpy.isin() method,     
we can see that one array having values are checked in a different numpy array having different elements with different sizes.

used to search multiple items at once in the array and return the value in the boolean.   

if added the value into the a[] than it will return the duplicate /finding number.

In [176]:
a

array([22, 78, 80, 64, 22,  5,  1,  5, 54, 65, 18, 48, 15, 82, 44, 62, 65,
       46, 38, 27])

In [186]:
np.isin(a,[64,16,82])

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False])

In [187]:
a[np.isin(a,[64,16,82])]

array([64, 82])

In [194]:
print(a)
l=[5,10,15,20,25,30,65,55,75,85,95]
print(l)

[22 78 80 64 22  5  1  5 54 65 18 48 15 82 44 62 65 46 38 27]
[5, 10, 15, 20, 25, 30, 65, 55, 75, 85, 95]


In [190]:
a[np.isin(a,l)]

array([ 5,  5, 65, 15, 65])

# np.flip()

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

reverse the array or show mirror image of the array 
it can flip 2d array row & cloumns

In [196]:
print(a)
print()
print(np.flip(a))

[22 78 80 64 22  5  1  5 54 65 18 48 15 82 44 62 65 46 38 27]

[27 38 46 65 62 44 82 15 48 18 65 54  5  1  5 22 64 80 78 22]


In [198]:
print(np.flip(b)) # flip row & columns 

[[17 63 40 99]
 [12 89 57 65]
 [82 88 85 84]
 [69 38 88 43]
 [12 90 40 85]
 [72 78 19 10]]


In [204]:
print(b)
print()
print(np.flip(b,axis=0)) # flip only rows

[[10 19 78 72]
 [85 40 90 12]
 [43 88 38 69]
 [84 85 88 82]
 [65 57 89 12]
 [99 40 63 17]]

[[99 40 63 17]
 [65 57 89 12]
 [84 85 88 82]
 [43 88 38 69]
 [85 40 90 12]
 [10 19 78 72]]


In [203]:
print(b)
print()
print(np.flip(b,axis=1)) # flip only columns

[[10 19 78 72]
 [85 40 90 12]
 [43 88 38 69]
 [84 85 88 82]
 [65 57 89 12]
 [99 40 63 17]]

[[72 78 19 10]
 [12 90 40 85]
 [69 38 88 43]
 [82 88 85 84]
 [12 89 57 65]
 [17 63 40 99]]


# np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

NOTE: it will permanent change in the orginal array
syntax:

np.put(array name, [index numbers, 2nd ind number], [new value, 2nd new value])

In [20]:
a

array([65, 29, 60, 15, 10,  1, 96, 35, 75, 76, 75, 68, 29, 29, 15, 82, 94,
       45,  5, 51])

In [21]:
np.put(a,[5,6],[50,110])

In [209]:
a

array([ 22,  78,  80,  64,  22,  50, 110,   5,  54,  65,  18,  48,  15,
        82,  44,  62,  65,  46,  38,  27])

# np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

delete single or multiple numbers on the basis of the index number of the values.

In [210]:
a

array([ 22,  78,  80,  64,  22,  50, 110,   5,  54,  65,  18,  48,  15,
        82,  44,  62,  65,  46,  38,  27])

In [212]:
np.delete(a,0)

array([ 78,  80,  64,  22,  50, 110,   5,  54,  65,  18,  48,  15,  82,
        44,  62,  65,  46,  38,  27])

In [218]:
np.delete(a,[0,5,7,9,13,6,18])

array([78, 80, 64, 22, 54, 18, 48, 15, 44, 62, 65, 46, 27])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [219]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [220]:
np.intersect1d(m,n)

array([3, 4, 5])

In [221]:
np.setdiff1d(n,m)

array([6, 7])

In [222]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [223]:
m[np.in1d(m,1)]

array([1])

# np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

make boundries of the value in the given range and     
replace the value with the min & max value if array value exceed the given range

In [224]:
a

array([ 22,  78,  80,  64,  22,  50, 110,   5,  54,  65,  18,  48,  15,
        82,  44,  62,  65,  46,  38,  27])

In [227]:
np.clip(a,a_min=25, a_max=75)

array([25, 75, 75, 64, 25, 50, 75, 25, 54, 65, 25, 48, 25, 75, 44, 62, 65,
       46, 38, 27])